global:
  env: local
  namespace: invest-compass-{{ .Values.global.env }}
  secrets:
    dbName: ''
    dbPassword: ''
    dbUsername: ''

apps:
  server:
    image: ''
    port: 13010
    debugPort: 13014
    config:
      port: 13010
      debugServer: 13014
