apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  namespace: {{ tpl .Values.namespace . }}
  labels:
    app.kubernetes.io/service: postgres-service
spec:
  selector:
    app.kubernetes.io/name: postgres
  {{- with .Values.service }}
    {{ toYaml . | nindent 2 }}
  {{- end }}
