{{- range $name, $app := .Values.apps }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $name }}
  namespace: {{ tpl $.Values.global.namespace $ }}
  labels:
    app.kubernetes.io/name: {{ $name }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ $name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ $name }}
    spec:
      containers:
        - name: {{ $name }}
          image: {{ $app.image }}
          # If an image does not exist local, then raise error.
          imagePullPolicy: Never
          ports:
            - containerPort: {{ $app.port }}
          env:
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: {{ tpl $.Values.global.namespace $ }}-secrets
                  key: db_name
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: {{ tpl $.Values.global.namespace $ }}-secrets
                  key: db_username
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ tpl $.Values.global.namespace $ }}-secrets
                  key: db_password
          volumeMounts:
            - name: {{ $name }}-config-volume
              mountPath: /config
              readOnly: true
          resources:
            requests:
              memory: 64Mi
              cpu: 100m
            limits:
              memory: 256Mi
              cpu: 500m
          readinessProbe:
            httpGet:
              path: /ready
              port: {{ $app.debugPort }}
            initialDelaySeconds: 5
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /health
              port: {{ $app.debugPort }}
            initialDelaySeconds: 30
            periodSeconds: 10
      volumes:
        - name: {{ $name }}-configmap-volume
          configMap:
            name: {{ $name }}-configmap
            items:
              - key: config.yaml
                path: config.yaml
{{- end }}
