apiVersion: v1
kind: Secret
metadata:
  name: {{ tpl .Values.global.namespace . }}-secrets
  namespace: {{ tpl .Values.global.namespace . }}
type: Opaque
data:
  dbName: ''
  dbPassword: ''
  dbUsername: ''
