{{- range $app := .Values.apps }}
apiVersion: v1
kind: Service
metadata:
  name: {{ $app.name }}
spec:
  selector:
    app.kubernetes.io/name: {{ $app.name }}
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
{{- end }}
