{{- range $name, $app := .Values.apps }}
apiVersion: v1
kind: Service
metadata:
  name: {{ $name }}-service
  namespace: {{ tpl $.Values.global.namespace $ }}
  labels:
    app.kubernetes.io/name: {{ $name }}
spec:
  selector:
    app.kubernetes.io/name: {{ $name }}
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 13010
      targetPort: {{ $app.port }}
    - protocol: TCP
      port: 13014
      targetPort: {{ $app.debugPort }}
{{- end }}
