global:
  env: local

nameSuffix: server

config:
  server:
    port: 8080
  debugServer:
    port: 8084
  postgres:
    db: ""
    user: ""
    password: ""
    host: postgres-service.postgres-local.svc.cluster.local
    port: 5432

secret:
  dbName: ''
  dbUser: ''
  dbPassword: ''

image:
  repository: invest-compass-server
  tag: 0.1.0
  pullPolicy: IfNotPresent

ports:
  - containerPort: 8080
    protocol: TCP
    name: http
  - containerPort: 8084
    protocol: TCP
    name: http-diag

service:
  type: LoadBalancer
  ports:
    - port: 80
      name: http
    - port: 84
      name: http-diag

resources:
  requests:
    memory: 128Mi
    cpu: 100m
  limits:
    memory: 256Mi
    cpu: 500m

configMap:
  data:
    config.yaml: |-
      {{ toYaml .Values.config }}
