global:
  env: local

nameSuffix: server

secret:
  dbName: ''
  dbUser: ''
  dbPassword: ''

image:
  repository: invest-compass-server
  tag: 0.1.0
  pullPolicy: IfNotPresent

ports:
  - containerPort: 8080
    protocol: TCP
    name: http
  - containerPort: 8084
    protocol: TCP
    name: http-diag

service:
  type: LoadBalancer
  ports:
    - port: 8080
      name: http
    - port: 8084
      name: http-diag

resources:
  requests:
    memory: 128Mi
    cpu: 100m
  limits:
    memory: 256Mi
    cpu: 500m
