apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "app.fullname" . }}-cm
  labels:
    {{- include "app.labels" . | nindent 4 }}
data:
{{- range $key, $value := .Values.configMap.data }}
  {{ $key }}: |-
    {{- tpl (printf $value) $ | nindent 4 }}
{{- end }}
