apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "app.fullname" . }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "app.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "app.labels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ include "app.fullname" . }}
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- with .Values.ports }}
          ports:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          env:
            - name: CONFIG_PATH
              value: /tmp/configs/config.yaml
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: {{ include "app.name" . }}-secret
                  key: dbName
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: {{ include "app.name" . }}-secret
                  key: dbUser
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "app.name" . }}-secret
                  key: dbPassword
          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{/*
          * TODO: Configure readiness and liveness probes.
          */}}
          volumeMounts:
            - name: {{ include "app.fullname" . }}-cm-volume
              mountPath: /tmp/configs
      volumes:
        - name: {{ include "app.fullname" . }}-cm-volume
          configMap:
            name: {{ include "app.fullname" . }}-cm
