apiVersion: v1
kind: Service
metadata:
  name: {{ include "app.name" . }}-service
  labels:
    {{- include "app.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "app.selectorLabels" . | nindent 4 }}
  {{- with .Values.service }}
    {{- toYaml . | nindent 2 }}
  {{- end }}
