openapi: 3.0.0
info:
  title: Index API
  description: Index API describes handlers to manage indexes
  version: 0.1.0

servers:
  - url: http://localhost:8080/api
    description: Server for local development

paths:
  /v1/indexes:
    get:
      operationId: GetIndexes
      tags:
        - indexes
      description: Returns an array of all available market indexes
      responses:
        '200':
          $ref: '#/components/responses/IndexesListResponse'
        'default':
          $ref: '../common/error.openapi.yaml#/components/responses/ErrorResponse'
components:
  responses:
    IndexesListResponse:
      description: Successful operation
      content:
        application/json:
          schema:
            type: object
            properties:
              indexes:
                type: array
                items:
                  $ref: '#/components/schemas/Index'
            required:
              - indexes
  schemas:
    Index:
      type: object
      required:
        - ticker
      properties:
        ticker:
          type: string
          maxLength: 10
          example: "SPX"
          description: Trading symbol of the index


